#!/bin/bash
# This filter avoids submitting tokens to the git repo. To use this:
#
# 1. Create a file ~/.cvp_download_token with your download token 
# 2. Add the following lines to your .git/config:
#
# [filter "remove-tokens"]
#   clean  = .gitfilters/remove-tokens-clean
#   smudge = .gitfilters/remove-tokens-smudge
set -e
sed 's/\(cvp_download_token.*=\) ".*"/\1 "PLACE_YOUR_PORTAL_TOKEN_HERE"/g'